name: BuildDeploy

on:
  push:
    branches:
      - siopv2_with_mfv2_terance_upgraded

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - name: Set env vars (common)
        run: |      
          echo "REMOTE_APP_FOLDER=~/apps/siopv2-demo" >> $GITHUB_ENV
          echo "REMOTE_SUB_FOLDER=/public/other" >> $GITHUB_ENV
          echo "REMOTE_FILE_NAME=siop-did-extension-1" >> $GITHUB_ENV
          echo "REMOTE_APP_BINARY=dist" >> $GITHUB_ENV
      - name: Set env vars (prod)
        if: endsWith(github.ref, '/siopv2_with_mfv2_terance_upgraded')
        run: |
          echo "REMOTE_APP_ENV=prod" >> $GITHUB_ENV
          echo "REMOTE_HOST="${{ secrets.SSH_HOST_PROD }} >> $GITHUB_ENV

      - uses: actions/checkout@master
      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run build

      - name: Compress build
      - uses: vimtor/action-zip@v1
        with:
          files: ${{ env.REMOTE_APP_BINARY }}/
          dest: ${{ env.REMOTE_FILE_NAME }}.zip

      - name: Copy build to server
        uses: nogsantos/scp-deploy@master
        with:
          src: ./${{ env.REMOTE_FILE_NAME }}.zip
          host: ${{ env.REMOTE_HOST }}
          remote: ${{ env.REMOTE_APP_FOLDER }}/${{ env.REMOTE_APP_ENV }}/${{ env.REMOTE_SUB_FOLDER }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}